### ISSUE TITLE
std::feature вместо std::future

### ISSUE THREAD

**Issue by Frumka** [bmstu-iu8-cpp/cpp-upper-intermediate#1]
cpp19/04_multithreads.pdf

Слайд 2. "Содержание" 
![Screenshot_2019-10-18-15-59-39-941_com adobe reader](https://user-images.githubusercontent.com/26420285/67096244-585cc380-f1c0-11e9-8987-9c46587ec668.png)

**Comment by drewxa** [comment]
Исправлено - https://bmstu-iu8-cpp.github.io/cpp-upper-intermediate/lec_04/#/1
